# Generated by Django 3.2.13 on 2023-05-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingoptions',
            name='intr_rate',
            field=models.FloatField(default=0),
        ),
    ]
