# Generated by Django 3.2.18 on 2023-05-18 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20230518_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositoptions',
            name='fin_prdt_cd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depositoptions', to='products.depositproducts'),
        ),
        migrations.AlterField(
            model_name='savingoptions',
            name='fin_prdt_cd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savingoptions', to='products.savingproducts'),
        ),
    ]
