# Generated by Django 3.2.13 on 2023-05-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='money',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='salary',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
