# Generated by Django 3.2.18 on 2023-05-18 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20230518_1234'),
        ('accounts', '0002_auto_20230518_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registered_products',
        ),
        migrations.AddField(
            model_name='user',
            name='financial_products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_products', to='products.savingproducts'),
        ),
    ]
